### ISSUE TITLE
No way to read from buffer？

### ISSUE THREAD

**Issue by winterland1989** [bgamari/ring-buffer#1]
i want to use this package to implemnet a lru cache, but i need a way to read latest n item from the buffer, can you provide something like:  `latest :: Vector v a => RingBuffer v a -> Int -> IO a` ?

**Comment by bgamari** [comment]
Sure. Give me a few minutes.

**Comment by bgamari** [comment]
@winterland1989 released as 0.2.0.

**Comment by winterland1989** [comment]
Thanks!
