### ISSUE TITLE
I there any way to "drain" RingBuffer?

### ISSUE THREAD

**Issue by qrilka** [bgamari/ring-buffer#4]
I was looking into some way to implement a "cache with overflow" and ring buffer looks like some way to do that.
But looking into `ring-buffer` haddocks I don't see a good way to "drain" the buffer - i.e. I want to write items one by one into it and another thread will just take all of the items making the buffer empty.
Is there any good way to do that or I should better switch to something else like channels?

**Comment by bgamari** [comment]
What form would you like the contents of the ringbuffer in?

**Comment by qrilka** [comment]
both list and `Vector` would be fine but as I understand with `ring-buffer` I will need to `freeze` and clear the buffer in 1 operation blocking other threads for O(n) units of time or I miss something?
So I've decided to start with using `unagi-chan` at least as a first attempt

**Comment by bgamari** [comment]
Indeed, the currently implementation doesn't admit an O(1) clear operation.

Good luck!
