### ISSUE TITLE
latest doesn't account for wrap around

### ISSUE THREAD

**Issue by dmwit** [bgamari/ring-buffer#7]
For example:

    Data.RingBuffer Data.Vector> x <- new 2 :: IO (RingBuffer Vector Int)
    Data.RingBuffer Data.Vector> append 0 x
    Data.RingBuffer Data.Vector> append 1 x
    Data.RingBuffer Data.Vector> append 2 x
    Data.RingBuffer Data.Vector> latest x 0
    Just 1

Looking at the implementation of `latest` and `latest'`, they don't even mention `ringHead` at all, which can't be right. This also affects the correctness of `toList` compared to its documented behavior.

**Comment by Lysxia** [comment]
In `latest'` the formula for `idx` should be `ringHead - n - 1`.

**Comment by bgamari** [comment]
Oh dear, that is terrible! Thank you for pointing this out. Fix coming.

**Comment by bgamari** [comment]
Fix released as 0.4.
